eventcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('about/', views.about, name='about'),
  path('events/', views.event_index, name='event-index'),
  path('events/<int:event_id>/', views.event_detail, name='event-detail'),
  path('events/create/', views.EventCreate.as_view(), name='event-create'),
  path('events/<int:pk>/update', views.EventUpdate.as_view(), name='event-update'),
  path('events/<int:pk>/delete', views.EventDelete.as_view(), name='event-delete'),
  path('accounts/signup/', views.signup, name='signup')
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
import datetime

from django.contrib.auth.models import User

# Create your models here.
CATEGORIES = (
  ('AR', 'Art'),
  ('CH', 'Charity'),
  ('CM', 'Comedy Show'),
  ('CN', 'Conference'),
  ('CO', 'Concert'),
  ('CS', 'Class / Seminar'),
  ('EX', 'Exercise / Fitness'),
  ('FA', 'Fashion'),
  ('FE', 'Festival'),
  ('FI', 'Film'),
  ('FO', 'Food'),
  ('FU', 'Fundraiser'),
  ('GA', 'Gala'),
  ('MU', 'Music'),
  ('NE', 'Networking'),
  ('OT', 'Other'),
  ('PA', 'Party'),
  ('SP', 'Sports'),
  ('TH', 'Theater'),
  ('WE', 'Wedding'),
  ('WR', 'Work Outing'),
)

CELEBRATION =(
  ('N', 'No'),
  ('Y', 'Yes'),
)

class Event(models.Model):
  name = models.CharField(max_length=150)
  date = models.DateField('Date', default=datetime.date.today)
  time = models.TimeField('Time', default=datetime.time(12, 0))
  category = models.CharField(max_length=2, choices=CATEGORIES, default='AR')
  venue = models.CharField(max_length=150)
  address = models.TextField(max_length=250)
  cost = models.DecimalField(max_digits=8, decimal_places=2, default= 0, help_text='Please enter the amount as a number without the "$" symbol, e.g., 0.00 or 0')
  celebration = models.CharField(max_length=1, choices=CELEBRATION, default=[0][0])
  description = models.TextField(max_length=250, blank=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  
  def __str__(self):
    return f"{self.get_category_display()} on {self.name}"
  
  def get_absolute_url(self):
    return reverse("event-detail", kwargs={"event_id": self.id})
  
  def event_passed(self):
    return self.date < timezone.now().date()

  class Meta:
    ordering = ['-date']

main_app/views.py
from django import forms
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Event
# Create your views here.

class Home(LoginView):
  template_name = 'home.html'

class CurrencyInput(forms.NumberInput):
  input_type = 'text'

class AddressInput(forms.TextInput):
  input_type = 'text'


def about(request):
  return render(request, 'about.html')

@login_required
def event_index(request): 
  events = Event.objects.filter(user=request.user)
  return render(request, 'events/index.html', {'events': events})

@login_required
def event_detail(request, event_id):
  event = Event.objects.get(id=event_id)
  return render(request, 'events/detail.html', {'event': event})

class EventCreate(LoginRequiredMixin, CreateView):
  model = Event
  fields = ['name', 'date', 'time', 'category', 'venue', 'address', 'cost', 'celebration', 'description']
  success_url = '/events/'

  def get_form(self, form_class=None):
    form = super().get_form(form_class)
    form.fields['date'].widget = forms.DateInput(attrs={'type': 'date'})
    form.fields['time'].widget = forms.TimeInput(attrs={'type': 'time'})
    form.fields['cost'].widget = CurrencyInput(attrs={'placeholder': '$'})
    form.fields['address'].widget = AddressInput(attrs={"placeholder": '123 Main St, City, State, ZIP, Country'})
    return form
  
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class EventUpdate(LoginRequiredMixin, UpdateView):
  model = Event
  fields = ['name', 'date', 'time', 'category', 'venue', 'address', 'cost', 'celebration', 'description']

  def get_form(self, form_class=None):
    form = super().get_form(form_class)
    form.fields['date'].widget = forms.DateInput(attrs={'type': 'date'})
    form.fields['time'].widget = forms.TimeInput(attrs={'type': 'time'})
    form.fields['cost'].widget = CurrencyInput(attrs={'placeholder': '$'})
    form.fields['address'].widget = AddressInput(attrs={"placeholder": '123 Main St, City, State, ZIP, Country'})
    return form
  
class EventDelete(LoginRequiredMixin, DeleteView):
  model = Event
  success_url = '/events/'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('event-index')
    else:
      error_message= 'Invalid signup - try again'
  form = UserCreationForm()
  context = {'form':form, 'error_message': error_message}
  return render(request, 'signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="about">
  <div class="aboutme">
    <h1 class="abouth1">About the Event Collector</h1>
    <img class="carla" src="{% static 'images/carla.png' %}" alt="github logo">
    <h2 class="abouth2">Carla Pacheco</h2>
    <p class="page-content">
      Software Engineer passionate about crafting technical solutions that bridge the gap between client needs and innovative products. My background is in marketing and e-commerce, primarily within MarTech and SaaS companies. Also, I am currently job seeking!
    </p>
    <div class="logos">
      <a href="https://github.com/cmpacheco23">
        <img src="{% static 'images/github.svg' %}" alt="github logo">
      </a>
      <a href="https://www.linkedin.com/in/thecarlapacheco/">
        <img src="{% static 'images/linkedin.png' %}" alt="LinkedIn logo">
      </a>
    </div>
    <div class="hr-container">
      <hr class="hr" />
    </div>
    
  </div>
  <div class="aboutapp">
    <h1 class="abouth1">About EventCaptcha</h1>
    <img class="logoapp" src="{% static 'images/logo.png' %}" alt="Event Captcha Logo" />
    <p class="page-content">
      EventCaptcha is your ultimate digital scrapbook for every event in your life, past, present, and future. Say goodbye to the hassle of forgetting memorable moments and missing out on exciting future gatherings. With EventKapture, you can effortlessly capture the essence of each event, creating a vivid and personal record that's as unique as you are.
    </p>
    <ul>
      <li>📌 📸 Capture the Magic: Snap photos, jot down notes, and record your thoughts to preserve the essence of every event you attend. From epic concerts and family gatherings to exciting vacations and future plans, EventKapture lets you treasure each moment.
      </li>
      <li>📌 🌟 Chronicle Your Journey: Create a captivating and fun chronicle of your event-filled life. Easily organize and revisit past events, anticipate upcoming adventures, and reflect on the wonderful tapestry of your experiences.
      </li>
      <li> 📌 📅 Never Miss a Beat: Stay on top of your event schedule with built-in reminders and calendars. Whether it's a concert, wedding, or simple meet-up with friends, EventKapture keeps you in the loop.
      </li>
    </ul>
  </div>

</section>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Rancho&display=swap" rel="stylesheet">
  <link
    rel="shortcut icon"
    type="image/png"
    href="{% static "images/favicon.png" %}"
  >
  <title>Event Collector</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <nav class="menu">
    <ul class="menulist">
      {% if user.is_authenticated %}
        <li>
          <a href="{% url "about" %}" class="navurl">About</a>
        </li>
        <li>
          <a href="{% url "event-index" %}" class="navurl">All Events</a>
        </li>
        <li>
          <a href="{% url "event-create" %}" class="navurl">Add Event</a>
        </li>
        <li>
          <a href="{% url "logout" %}" class="navurl">Log out</a>
        </li>
      {% else %}
        <li>
          <a href="{% url "about" %}" class="navurl">About</a>
        </li>
        <li>
          <a href="{% url "home" %}" class="navurl">Login</a>
        </li>
        <li>
          <a href="{% url "signup" %}" class="navurl">Sign Up</a>
        </li>
      {% endif %}
    </ul>      
  </nav>

  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/events/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/events/event-detail.css' %}"
/>

{% endblock %}

{% block content %}

<section class="event-container">
  <div class="event-image">
    {% with category_code=event.category %}
    <img 
      src="{% static 'images/category_images/' %}{% if category_code %}{{ category_code }}.png{% else %}default.png{% endif %}"
      alt="Category: {{ event.get_category_display }}"
    >
  {% endwith %}
  </div>
  <div class="event-details">
    {% if not event.event_passed %}
      <p class="event-passed">This event is coming up soon!</p>
    {% else %}
      <p class="event-passed">This event has already passed!</p>
    {% endif %}
    <h1>{{ event.name }}</h1>
    <div class="event-actions">
      <a href="{%url 'event-update' event.id%}" class="button-86 btn warn">Edit</a>
      <a href="{%url 'event-delete' event.id%}" class="button-86 btn danger">Delete</a>
    </div>
    <h3>Date: {{ event.date }}</h3>
    <h3>Time: {{ event.time }}</h3>
    <h3>Category: {{ event.get_category_display }}</h3>
    <h3>Venue: {{ event.venue }}</h3>
    <h3>Address: {{ event.address }}</h3>
    <h3>Cost: ${{ event.cost }}</h3>
    <h3>Celebration: {{ event.get_celebration_display }}</h3>
    <p>{{ event.description }}</p>
  </div>
</section>

{% endblock %}

main_app/templates/events/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/events/event-index.css' %}"
/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>Event List</h1>
  <img class="event-icon" src="{% static 'images/35.png' %}" alt="Gold balloons" />
  <img class="event-icon" src="{% static 'images/34.png' %}" alt="A blue round callendar" />
  <img class="event-icon" src="{% static 'images/36.png' %}" alt="Admission tickets admit one" />
</section>

<section class="card-container">
  {% for event in events %}
    <div class="card">
      <a href="{%url 'event-detail' event.id%}">
        <div class="card-content">
          <div class="card-img-container">
            {% with category_code=event.category %}
              <img 
                src="{% static 'images/category_images/' %}{% if category_code %}{{ category_code }}.png{% else %}default.png{% endif %}"
                alt="Category: {{ event.get_category_display }}"
              >
            {% endwith %}
          </div>
          <h2 class="card-title">{{ event.name }}</h2>
          {% if not event.event_passed %}
            <p>This event is on: {{ event.date }}</p>
          {% else %}
            <p>This event took place on: {{ event.date }}</p>
          {% endif %}
          <p><small>{{ event.description }}</small></p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

{% if not user.is_authenticated %}
<section>
  <div class="event-container">
    <img src="{% static 'images/logo.png' %}" alt="Event Captcha Logo" />
  </div>
  <form action="{%url 'home'%}" method="post" class="login">
    <h1>Login</h1>
    {% csrf_token %}
    {{form.as_p}}
    <input type="hidden" name="next" value="{{next}}">
    <button type="submit" class="btn submit button-86 loginbtn">Login</button>
  </form>
</section>
{% endif %}
{% endblock %}

main_app/templates/main_app/event_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="deleteit">
  <img src="{% static 'images/nerd-cat.svg' %}" alt=""/>
  <h1 class="h1delete">Want To Delete Event?</h1>
</div>
<h2 class="h2delete">Are you sure you want to delete {{ event.name }}?</h2>

<form action="" method="post" class="form" id="deleteform">
  {% csrf_token %}
  <div class="deletesection">
    <a 
      href="{% url 'event-detail' event.id %}" 
      class="btn secondary button-86 deletepg"
    >
      Cancel
    </a>
    <button type="submit" class="btn danger button-86 deletepg">Yes - Delete!</button>
  </div>
</form>

{% endblock %}

main_app/templates/main_app/event_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>

<script defer src="{% static "js/event-form.js" %}"></script>
{% endblock %}

{% block content %}
<div class="page-header">
  {% if event %}
    <h1>Edit {{event.name}}</h1>
  {% else %}
    <h1>Add an Event</h1>
  {% endif %}
  <img class="event-icon" src="{% static 'images/34.png' %}" alt="A blue round callendar" />
</div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit button-86" >Submit</button>
</form>
{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1 class="signup">Sign Up</h1>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" id="signupform" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit button-86">Submit</button>
</form>

{% endblock %} 